version: "3"

services:
  bot:
    container_name: nextcord-test
    env_file: .env
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/bot/logs
      - ./nextcord_test:/bot/nextcord_test
